### ISSUE TITLE
google-service.json required?

### ISSUE THREAD

**Issue by parwanto** [codigo-cyberlin-metadata/seedroid#3]
Hi there,

I'm try to create a new project, but after setting the Gradle(app) I got this notice:

> Error:Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  ...\app\src\debug\google-services.json
  ...\app\google-services.json

is the google service is requeired?

**Comment by 672009095** [comment]
yes it's required for GA,
u can read again on readme, i was update for this issue.
comment here again if not yet solve. thanks.

**Comment by parwanto** [comment]
hi @672009095 thanks for the reply, on readme

> if you find issue google-service.json not found you can add inside main folder your project by copy or download from there:

if I want to download from firebase console, it's the same way?

**Comment by 672009095** [comment]
ya that's good to, u can integrate your project into firebase console if u get or have email from your product owner for your project and for maintain your analytics, but if u not yet have an email better is use copy of google service because on firebase u cant integrate 2 project with same package, and hard to migration from your email to product owner email.
